name: Weekly Marketplace Ranking Report

on:
  schedule:
    - cron: "0 9 * * 0"   # 매주 일요일 18:00 KST (UTC 09:00)
  workflow_dispatch: {}

jobs:
  weekly:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Print current time (UTC & KST)
        run: |
          echo "=== UTC Time ==="
          date -u
          echo "=== KST Time ==="
          TZ=Asia/Seoul date

      - name: Run weekly report
        env:
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          python weekly_report.py
