name: oliveyoung-mobile-brand-ranking

on:
  workflow_dispatch:
  schedule:
    # 한국시간 09:10 (UTC 00:10)
    - cron: "10 0 * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      PLAYWRIGHT_BROWSERS_PATH: 0  # 러너 작업 디렉토리에 브라우저 설치(경로 이슈 방지)

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 openpyxl google-api-python-client google-auth google-auth-httplib2 google-auth-oauthlib playwright playwright-stealth
          # 브라우저 설치 (chromium / webkit)
          python -m playwright install --with-deps chromium webkit

      - name: Run crawler
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
        run: |
          python app_brand.py
