name: Weekly Report

on:
  workflow_dispatch:
  schedule:
    # 매주 월요일 KST 오전 03:30 (UTC 일 18:30)
    - cron: '30 18 * * 0'

env:
  PYTHON_VERSION: '3.11'
  DATA_DIR: ./data/daily
  DIST_DIR: ./dist

jobs:
  weekly:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ensure data/output dirs
        run: |
          mkdir -p "${DATA_DIR}" "${DIST_DIR}"

      # === (선택) 구글 드라이브에서 일일 CSV 내려받기 ===
      - name: Fetch daily CSVs from Google Drive (optional)
        if: ${{ secrets.GDRIVE_FOLDER_ID != '' && secrets.GOOGLE_CLIENT_ID != '' && secrets.GOOGLE_CLIENT_SECRET != '' && secrets.GOOGLE_REFRESH_TOKEN != '' }}
        env:
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
        run: |
          python scripts/fetch_from_gdrive.py

      # === (선택) 일일 데이터 간단 스캔 ===
      - name: Quick scan (optional)
        run: |
          python scripts/check_daily_scan.py || true

      # === 주간 집계 생성(소스별 텍스트 + JSON 등) ===
      - name: Generate weekly report (per source)
        run: |
          python scripts/weekly_report_plus.py --src all --data-dir "${DATA_DIR}"

      # === (선택) 슬랙 전송: 소스별로 개별 메시지 ===
      - name: Send to Slack (optional)
        if: ${{ secrets.SLACK_WEBHOOK_URL != '' }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          set -e
          post(){ 
            BODY=$(jq -Rs . < "$1");
            curl -sS -X POST -H 'Content-type: application/json' \
              --data "{\"text\": ${BODY}}" "${SLACK_WEBHOOK_URL}" >/dev/null; 
          }
          post slack_oy_kor.txt
          post slack_oy_global.txt
          post slack_amazon_us.txt
          post slack_qoo10_jp.txt
          post slack_daiso_kr.txt

      # === HTML 리포트 생성 (하이퍼링크 포함) ===
      - name: Build HTML
        run: |
          python scripts/build_html_report.py --out "${DIST_DIR}/weekly_report.html"
          ls -l "${DIST_DIR}"

      # === (선택) 구글 드라이브 업로드 ===
      - name: Upload HTML to Google Drive (optional)
        if: ${{ secrets.GDRIVE_FOLDER_ID != '' && secrets.GOOGLE_CLIENT_ID != '' && secrets.GOOGLE_CLIENT_SECRET != '' && secrets.GOOGLE_REFRESH_TOKEN != '' }}
        env:
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
        run: |
          python scripts/upload_to_gdrive.py "${DIST_DIR}/weekly_report.html" "${GDRIVE_FOLDER_ID}"

      # === 산출물 보관 ===
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: weekly-report
          path: ${{ env.DIST_DIR }}
