name: Weekly Report

on:
  workflow_dispatch:
  schedule:
    # 매주 월요일 07:00 KST (일 22:00 UTC)
    - cron: "0 22 * * 0"

concurrency:
  group: weekly-report
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  weekly:
    runs-on: ubuntu-latest

    env:
      DATA_DIR: ./data/daily
      DIST_DIR: ./dist

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ensure data/output dirs
        run: |
          mkdir -p "${DATA_DIR}"
          mkdir -p "${DIST_DIR}"

      # ---------------------------
      # Google Drive에서 일일 CSV 가져오기 (옵션)
      # -> if: 대신 쉘 가드로 비밀키 확인
      # ---------------------------
      - name: Fetch daily CSVs from Google Drive (optional)
        env:
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
        run: |
          if [ -z "${GDRIVE_FOLDER_ID}" ] || [ -z "${GOOGLE_CLIENT_ID}" ] || [ -z "${GOOGLE_CLIENT_SECRET}" ] || [ -z "${GOOGLE_REFRESH_TOKEN}" ]; then
            echo "[GDRIVE] secrets missing -> skip fetch"
            exit 0
          fi
          python scripts/fetch_from_gdrive.py || true

      - name: Quick scan (optional)
        run: |
          echo "== data files =="; ls -l "${DATA_DIR}" || true

      - name: Generate weekly report (per source)
        run: |
          python scripts/weekly_report_plus.py --src all --data-dir "${DATA_DIR}"

      # ---------------------------
      # Slack 전송 (옵션) — 쉘 가드 사용
      # ---------------------------
      - name: Send to Slack (optional)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          if [ -z "${SLACK_WEBHOOK_URL}" ]; then
            echo "[SLACK] webhook not set -> skip"
            exit 0
          fi

          post() {
            local f="$1"
            if [ -f "$f" ]; then
              BODY="$(jq -Rs . < "$f")"
              curl -sS -X POST -H 'Content-type: application/json' \
                --data "{\"text\":${BODY}}" "$SLACK_WEBHOOK_URL" >/dev/null
              echo "posted: $f"
            fi
          }

          post dist/slack_oy_kor.txt
          post dist/slack_oy_global.txt
          post dist/slack_amazon_us.txt
          post dist/slack_qoo10_jp.txt
          post dist/slack_daiso_kr.txt

      - name: Build HTML
        run: |
          python scripts/build_html_report.py
          echo "== HTML files =="; ls -l dist

      # ---------------------------
      # Google Drive로 HTML 업로드 (옵션) — 쉘 가드 사용
      # ---------------------------
      - name: Upload HTML to Google Drive (optional)
        env:
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
        run: |
          if [ -z "${GDRIVE_FOLDER_ID}" ] || [ -z "${GOOGLE_CLIENT_ID}" ] || [ -z "${GOOGLE_CLIENT_SECRET}" ] || [ -z "${GOOGLE_REFRESH_TOKEN}" ]; then
            echo "[GDRIVE] secrets missing -> skip upload"
            exit 0
          fi
          python scripts/upload_to_gdrive.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: weekly-report
          path: dist/*
