name: Weekly Beauty Ranking Analysis

on:
  schedule:
    - cron: '0 10 * * 0'  # 일요일 오후 7시 KST (UTC 기준 오전 10시)
  workflow_dispatch:  # 수동 실행도 가능하도록

jobs:
  weekly-analysis:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client requests python-dotenv

    - name: Run weekly analysis
      env:
        GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
        GOOGLE_CLIENT_EMAIL: ${{ secrets.GOOGLE_CLIENT_EMAIL }}
        GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        python scripts/weekly_analysis.py

    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add reports/weekly_report_$(date +%Y-%m-%d).md
        git commit -m "Add weekly report for $(date +%Y-%m-%d)" || echo "No changes to commit"
        git push
