name: Weekly Report → Slack + Google Drive (HTML)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"  # 매주 월요일 09:00 KST (UTC 00:00)

jobs:
  weekly:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          python -m pip install --upgrade pip
          pip install pandas google-api-python-client google-auth-httplib2 google-auth-oauthlib

      # 1) (필요 시) 구글 드라이브에서 일일 CSV 받기
      - name: Fetch daily CSVs from Google Drive
        env:
          GOOGLE_CLIENT_ID:     ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
          GDRIVE_FOLDER_ID:     ${{ secrets.GDRIVE_FOLDER_ID }}
        run: |
          mkdir -p data/daily
          python scripts/fetch_from_gdrive.py || true
          echo "== data/daily =="
          ls -al data/daily || true

      # 2) 소스별 주간 리포트(슬랙 txt & 요약 json) 생성
      - name: Generate weekly reports (all sources)
        env:
          DATA_DIR: ./data/daily
          MIN_DAYS: 3
        run: |
          for SRC in oy_kor oy_global amazon_us qoo10_jp daiso_kr; do
            echo ">>> generate $SRC"
            python scripts/weekly_report_plus.py \
              --src "$SRC" \
              --split \
              --data-dir "$DATA_DIR" \
              --min-days $MIN_DAYS || true
            # 파일이 없으면 기본값 생성(슬랙/HTML/메일 안전)
            [ -f "slack_${SRC}.txt" ] || echo "데이터 없음" > "slack_${SRC}.txt"
            [ -f "weekly_summary_${SRC}.json" ] || echo '{"range":"데이터 없음"}' > "weekly_summary_${SRC}.json"
          done

      # 3) 슬랙 전송 (섹션별 순차 전송)
      - name: Post to Slack
        if: ${{ secrets.SLACK_WEBHOOK_URL != '' }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          post(){
            BODY=$(jq -Rs . < "$1")
            curl -sS -X POST -H 'Content-type: application/json' \
              --data "{\"text\": ${BODY} }" "$SLACK_WEBHOOK_URL" > /dev/null
          }
          post slack_oy_kor.txt
          post slack_oy_global.txt
          post slack_amazon_us.txt
          post slack_qoo10_jp.txt
          post slack_daiso_kr.txt

      # 4) HTML 합본 생성
      - id: build_html
        run: |
          HTML_FILE=$(python scripts/build_html_report.py)
          echo "html=$HTML_FILE" >> "$GITHUB_OUTPUT"
          echo "built: $HTML_FILE"

      # 5) Google Drive 업서트(파일명: weekly_YYYY_MM_DD_YYYY_MM_DD.html)
      - name: Upload HTML to Google Drive
        env:
          GOOGLE_CLIENT_ID:     ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
          GDRIVE_FOLDER_ID:     ${{ secrets.GDRIVE_FOLDER_ID }}
        run: |
          python scripts/upload_to_gdrive.py "${{ steps.build_html.outputs.html }}"
