name: Weekly Report → Slack + Google Drive

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"  # 매주 월요일 09:00 KST (UTC 00:00)

jobs:
  weekly:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        src: [oy_kor, oy_global, amazon_us, qoo10_jp, daiso_kr]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas google-api-python-client google-auth-httplib2 google-auth-oauthlib

      - name: Generate weekly report
        env:
          DATA_DIR: ./data/daily
          MIN_DAYS: 3
          FLASH_MAX_DAYS: 2
        run: |
          python scripts/weekly_report_plus.py \
            --src ${{ matrix.src }} \
            --split \
            --data-dir "$DATA_DIR" \
            --min-days $MIN_DAYS

      - name: Upload to Google Drive
        env:
          GOOGLE_CLIENT_ID:     ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
          GDRIVE_FOLDER_ID:     ${{ secrets.GDRIVE_FOLDER_ID }}
        run: |
          python scripts/upload_to_gdrive.py \
            slack_${{ matrix.src }}.txt \
            weekly_summary_${{ matrix.src }}.json

      - name: Send to Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          # 파일 내용을 안전하게 JSON 문자열로 인코딩한 뒤 Webhook으로 전송
          BODY=$(cat slack_${{ matrix.src }}.txt | jq -Rs .)
          curl -sS -X POST -H 'Content-type: application/json' \
            --data "{\"text\": $BODY}" \
            "$SLACK_WEBHOOK_URL"
