name: Weekly Report → Email

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"  # 매주 월요일 09:00 KST (UTC 00:00)

jobs:
  weekly:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        src: [oy_kor, oy_global, amazon_us, qoo10_jp, daiso_kr]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: Generate weekly report (per source)
        env:
          DATA_DIR: ./data/daily
          MIN_DAYS: 3
          FLASH_MAX_DAYS: 2
        run: |
          python scripts/weekly_report_plus.py \
            --src ${{ matrix.src }} \
            --split \
            --data-dir "$DATA_DIR" \
            --min-days $MIN_DAYS

      # 메타(제목/기간) 추출
      - id: meta
        run: |
          RANGE=$(jq -r '.range // "데이터 없음"' weekly_summary_${{ matrix.src }}.json)
          case "${{ matrix.src }}" in
            oy_kor)    TITLE="올리브영 국내 Top100" ;;
            oy_global) TITLE="올리브영 글로벌 Top100" ;;
            amazon_us) TITLE="아마존 US Top100" ;;
            qoo10_jp)  TITLE="큐텐 재팬 뷰티 Top200" ;;
            daiso_kr)  TITLE="다이소몰 뷰티/위생 Top200" ;;
          esac
          echo "range=$RANGE" >> $GITHUB_OUTPUT
          echo "title=$TITLE" >> $GITHUB_OUTPUT

      # 본문(슬랙 텍스트 파일) 읽기
      - id: body
        run: |
          echo "text<<'EOF'" >> $GITHUB_OUTPUT
          if [ -f slack_${{ matrix.src }}.txt ]; then
            cat slack_${{ matrix.src }}.txt >> $GITHUB_OUTPUT
          else
            echo "데이터 없음" >> $GITHUB_OUTPUT
          fi
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Send report via Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_HOST }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          from: ${{ secrets.MAIL_FROM }}
          to: ${{ secrets.MAIL_TO }}
          subject: "[주간 리포트] ${{ steps.meta.outputs.title }} (${{ steps.meta.outputs.range }})"
          content_type: text/plain; charset=UTF-8
          body: ${{ steps.body.outputs.text }}
          attachments: |
            weekly_summary_${{ matrix.src }}.json
            slack_${{ matrix.src }}.txt
