name: Weekly report

on:
  workflow_dispatch: {}
  schedule:
    # 매주 일요일 18:00 KST (= 09:00 UTC)
    - cron: "0 9 * * 0"

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests

      - name: Fetch daily CSVs from Google Drive
        env:
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
          DATA_DIR: ./data/daily
        run: |
          python scripts/fetch_from_gdrive.py

      - name: Quick scan (optional)
        env:
          DATA_DIR: ./data/daily
        run: |
          python scripts/check_daily_scan.py || true

      - name: Run weekly report
        env:
          DATA_DIR: ./data/daily
          MIN_DAYS: 1   # 첫 실행 OK 확인 후 3으로
        run: |
          python scripts/weekly_report_v2.py | tee weekly_summary.json
          test -s weekly_summary.json || echo "{}" > weekly_summary.json

      - name: Post to Slack (optional)
        if: env.SLACK_WEBHOOK_URL != ''
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          payload=$(jq -n --arg t "$(cat weekly_summary.json)" '{text:$t}')
          curl -s -X POST -H 'Content-type: application/json' \
            --data "$payload" "$SLACK_WEBHOOK_URL" || true
